# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'steadii' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for steadii

  target 'steadiiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'steadiiUITests' do
    # Pods for testing
  end
  pod 'Firebase/Core'
  

end
